name: Create production promotion pull request.
on:
  push:
    branches:
      - staging
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Reset promotion branch
        run: |
          git fetch origin staging:staging
          git reset --hard staging
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Release to production
          body: This is an automated release PR. When you're ready to release, approve and `Merge Commit` this PR
          branch: master-promotion