name: Create a PR to deploy to master from staging
on:
  push:
    branches:
      - staging
jobs:
  productionPR:
    runs-on: ubuntu-latest
    steps:
    steps:
    - uses: actions/checkout@v2
      with:
        ref: staging
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: master