name: Testing workflow
on:
  pull_request:
    branches:
      - master
    types: [labeled]
jobs:
  destroy-staging:
    if: contains(github.event.pull_request.labels.*.name, 'tested-in-staging')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set formatted environment name
      run: |
        LOWERCASE_NAME="$(echo ${GITHUB_REF:11} | tr '[A-Z]' '[a-z]')"
        echo "::set-env name=ENV_NAME::$LOWERCASE_NAME"
    - name: Announce branch
      run: echo branch $ENV_NAME
