name: Testing workflow
on:
  pull_request:
    branches:
      - master
    types: [labeled]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.GHA}}
        ref: ${{ github.event.pull_request.base.ref }}
    - name: Set formatted environment name
      run: |
        if: contains(github.event.pull_request.labels.*.name, 'test-label')
        LOWERCASE_NAME="$(echo ${GITHUB_REF} | tr '[A-Z]' '[a-z]')"
        echo "::set-env name=ENV_NAME::$LOWERCASE_NAME"
    - name: Announce branch
      run: echo branch $ENV_NAME
