name: Testing workflow...
on:
  pull_request:
    branches:
      - master
    types: [labeled]
jobs:
  destroy-staging:
    if: contains(github.event.pull_request.labels.*.name, 'tested-in-staging')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.GHA}}
        ref: ${{ github.event.pull_request.base.ref }}
    - name: Set formatted environment name
      run: |
      
        LOWERCASE_NAME="$(echo ${{github.event.number}} | tr '[A-Z]' '[a-z]')"
        echo "::set-env name=ENV_NAME::$LOWERCASE_NAME"
    - name: Announce branch
      run: echo branch $ENV_NAME
